# Build stage
FROM node:24-alpine AS builder

WORKDIR /app

# Copy package files
COPY package.json ./

# Copy docs file
COPY doc/api.yaml ./doc/api.yaml

# Install dependencies
RUN npm cache clean --force
RUN npm install --legacy-peer-deps

# Copy source code and prisma schema
COPY . .

# Generate Prisma Client code
RUN npx prisma generate

# Copy entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Remove unnecessary files
RUN rm -rf /tmp/* /var/cache/apk/* /root/.npm /root/.cache

# Expose port
EXPOSE 4000

# Set entrypoint
ENTRYPOINT ["docker-entrypoint.sh"]

# Start the application (default command, can be overridden)
CMD ["npm", "run", "start:dev"]

