version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: home-library-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - home-library-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: ${POSTGRES_HEALTHCHECK_INTERVAL:-10s}
      timeout: ${POSTGRES_HEALTHCHECK_TIMEOUT:-5s}
      retries: ${POSTGRES_HEALTHCHECK_RETRIES:-5}

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: home-library-app1
    environment:
      PORT: ${PORT}
      BASE_URL: ${BASE_URL}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_SECRET_REFRESH_KEY: ${JWT_SECRET_REFRESH_KEY}
      TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
      TOKEN_REFRESH_EXPIRE_TIME: ${TOKEN_REFRESH_EXPIRE_TIME}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FILE_SIZE_KB: ${LOG_FILE_SIZE_KB}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /app/node_modules
    networks:
      - home-library-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: npm run start:dev
    develop: 
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - dist/

networks:
  home-library-network:
    driver: bridge

volumes:
  postgres_data:
  postgres_logs:

